### PR TITLE
[API-1172] Added queryAll method which surrounds the node.js oracledb…

### PR DESCRIPTION
**Pull request by vladimir-trifonov**
…'s driver limitation for rows count being returned by query.

https://jira.appcelerator.org/browse/API-1172

### CODE REVIEW

**Comment by janvennemann** [comment]
Any particular reason why you switched to `ResultSet` and didn't use the `maxRows` option for the existing `_query`utility method?

**Comment by vladimir-trifonov** [comment]
Hi Jan, there is not particular reason, It's just that you can't never be sure with the maxRow that it will returns all the rows, but it won't be a problem to use maxRows let's say with 100000. But in the current case, it's something that we do on initialization it thought that using ResultSet is not such a bad idea. What do you think, is it better to switch to maxRow over ResultSet?

**Comment by vladimir-trifonov** [comment]
@janvennemann What do you think of passing the query vars and method options under one param in the query method('data' param, _query.js -> row 11)?

**Comment by janvennemann** [comment]
Hm, i don't like mixing parameters for different purposes. Introducing another parameter just for options would be a cleaner solution, although passing that many parameters around becomes messy but well, the lesser of two evils i would say. God, i already hate this utility method, also who thought using two different callbacks just to avoid error checking was a good idea? 😐 

Anyway the rest of it looks good! So just add a options parameter after data and use lodash to determine if either data or options was used when the param count is four. That way the calls to `_query` in other model methods can stay the same.

While you are at it rename `processResultSet` to something more descriptive like`fetchRowsFromResultSet` and change to name of the `queryAll` option to `useResultSet`. (Sorry, i'm rather picky when it comes to naming stuff :D)

**Comment by vladimir-trifonov** [comment]
Yes, I'm agree with you, mixing parameters is a mess, I just decided that one parameter for options and variables is the only option since query method is used internal by arrow-orm, but in the end I added a new parameter like you proposed  and now it's working fine. Also I renamed the method and the option, I agree that it's more clear with the new names :)

**Comment by janvennemann** [comment]
CR and FT passed! Approved!

**Pull request merged**
